{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  replicas: {{ .Values.postgres.replicaCount }}
  strategy:
    type: {{ .Values.postgres.strategy }}

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}

          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}

          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database | quote }}

            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.username | quote }}

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.auth.existingSecret }}
                  key: {{ .Values.postgres.auth.passwordKey }}

          resources:
{{ toYaml .Values.postgres.resources | nindent 12 }}

          {{- if .Values.postgres.probes.startup.enabled }}
          startupProbe:
            exec:
              command:
                - pg_isready
                - -h
                - "127.0.0.1"
                - -p
                - {{ .Values.postgres.service.port | quote }}
                - -U
                - {{ .Values.postgres.auth.username | quote }}
                - -d
                - {{ .Values.postgres.auth.database | quote }}
            initialDelaySeconds: {{ .Values.postgres.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.postgres.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.postgres.probes.startup.failureThreshold }}
          {{- end }}

          {{- if .Values.postgres.probes.readiness.enabled }}
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - "127.0.0.1"
                - -p
                - {{ .Values.postgres.service.port | quote }}
                - -U
                - {{ .Values.postgres.auth.username | quote }}
                - -d
                - {{ .Values.postgres.auth.database | quote }}
            initialDelaySeconds: {{ .Values.postgres.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.postgres.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.postgres.probes.readiness.failureThreshold }}
          {{- end }}

          {{- if .Values.postgres.probes.liveness.enabled }}
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - "127.0.0.1"
                - -p
                - {{ .Values.postgres.service.port | quote }}
                - -U
                - {{ .Values.postgres.auth.username | quote }}
                - -d
                - {{ .Values.postgres.auth.database | quote }}
            initialDelaySeconds: {{ .Values.postgres.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.postgres.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.postgres.probes.liveness.failureThreshold }}
          {{- end }}

          {{- if .Values.postgres.persistence.enabled }}
          volumeMounts:
            - name: postgres-storage
              mountPath: {{ .Values.postgres.persistence.mountPath }}
          {{- end }}

      {{- if .Values.postgres.persistence.enabled }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.persistence.claimName }}
      {{- end }}
{{- end }}