{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  replicas: {{ .Values.redis.replicaCount }}

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}

          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}

          resources:
{{ toYaml .Values.redis.resources | nindent 12 }}

          {{- if .Values.redis.probes.startup.enabled }}
          startupProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: {{ .Values.redis.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.redis.probes.startup.failureThreshold }}
          {{- end }}

          {{- if .Values.redis.probes.readiness.enabled }}
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: {{ .Values.redis.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.redis.probes.readiness.failureThreshold }}
          {{- end }}

          {{- if .Values.redis.probes.liveness.enabled }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: {{ .Values.redis.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.redis.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.redis.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.redis.probes.liveness.failureThreshold }}
          {{- end }}
{{- end }}
